server:
  port: 8080

spring:
  application:
    name: gateway
  
  cloud:
    gateway:
      mvc:
        routes:
          # Authentication Service
          - id: auth-service
            uri: http://localhost:8081
            predicates:
              - Path=/auth/**
          
          # Message Service
          - id: message-service
            uri: http://localhost:8082
            predicates:
              - Path=/messages/**
          
          # Channel Service 
          - id: channel-service
            uri: http://localhost:8083
            predicates:
              - Path=/channels/**
          
          # Push Service 
          - id: push-service
            uri: http://localhost:8084
            predicates:
              - Path=/push/**

# Configuration des logs
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    com.alom: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"