server:
  port: 8081

spring:
  application:
    name: auth
  data:
    mongodb:
      host: localhost
      port: 27017
      database: alom-auth
      auto-index-creation: true

logging:
  level:
    com.alom.auth: DEBUG