server:
  port: 8081

spring:
  application:
    name: auth
  data:
    mongodb:
      uri: mongodb://alom:alom@localhost:27017/alom-auth?authSource=admin
      auto-index-creation: true

logging:
  level:
    com.alom.auth: DEBUG