spring:
  application:
    name: message
  
  data:
    mongodb:
      uri: mongodb://localhost:27017/alom_messages
      auto-index-creation: true
  
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      group-id: message-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: "message:com.alom.message.dto.MessageDTO"
        # Rafraîchir les metadata toutes les 10 secondes pour découvrir les nouveaux topics
        metadata.max.age.ms: 10000
      auto-offset-reset: earliest

server:
  port: 8082

logging:
  level:
    com.alom.message: DEBUG
    org.springframework.kafka: INFO
